name: Hello World Training Workflow

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    env:
      MY_ENV: "John Doe" # Add custom environment variable
    steps:
      - name: Greet the User
        run: echo "Hello World!"
      
      # List all files in the current directory before checkout
      - name: List files before checkout
        run: ls -l
      
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2
      
      # List all files in the current directory after checkout
      - name: List files after checkout
        run: ls -l
      
      # Use environment variables in a multi-line script
      - name: Run a multi-line script
        run: |
          echo "Hello $MY_ENV"
          echo "Hello $GITHUB_ACTOR"
