name: CI with Coverage Report

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run Vitest Coverage Report
        uses: davelosert/vitest-coverage-report-action@v2.8.0
        with:
          output-directory: ./coverage
